# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=250)),
                ('project_name', models.CharField(max_length=250)),
                ('client_name', models.CharField(max_length=250)),
                ('deadline', models.DateTimeField(blank=True, default=False, verbose_name='absolute dealine')),
                ('project_type', models.CharField(choices=[('I', 'Invitation'), ('L', 'Logo'), ('D', 'Dayof'), ('S', 'Syleshoot'), ('A', 'Addressing')], max_length=1)),
            ],
        ),
    ]
