# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=250, null=True)),
                ('project_name', models.CharField(max_length=250, null=True)),
                ('client_name', models.CharField(max_length=250, null=True)),
                ('deadline', models.DateTimeField(default=False, null=True)),
                ('project_type', models.CharField(choices=[(b'I', b'Invitation'), (b'L', b'Logo'), (b'D', b'Dayof'), (b'S', b'Syleshoot'), (b'A', b'Addressing')], max_length=1, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('active', models.BooleanField(default=True)),
                ('photos', models.ManyToManyField(blank=True, to='digiapi.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[(b'P', b'In Progress'), (b'C', b'Complete'), (b'R', b'In Review')], max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[(b'L', b'Low'), (b'M', b'Med'), (b'H', b'High')], max_length=1, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together=set([('title', 'detail', 'status', 'created', 'priority')]),
        ),
        migrations.AddField(
            model_name='project',
            name='todos',
            field=models.ManyToManyField(blank=True, to='digiapi.Todo'),
        ),
    ]
