# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
