# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0002_auto_20161008_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
