# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0002_auto_20160124_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='poster',
            field=models.ImageField(default=datetime.datetime(2016, 2, 1, 1, 1, 28, 368222, tzinfo=utc), upload_to=b'/static/img'),
            preserve_default=False,
        ),
    ]
