# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0004_auto_20160131_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(upload_to='/static/img'),
        ),
    ]
