# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0005_auto_20160201_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(upload_to=b'/Users/adaro/AWS/aws-django/eb_django_app/static/img'),
        ),
    ]
