# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0006_auto_20160201_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(null=True, upload_to=b'/Users/adaro/AWS/aws-django/eb_django_app/static/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[(b'I', b'Invitation'), (b'L', b'Logo'), (b'D', b'Dayof'), (b'S', b'Syleshoot'), (b'A', b'Addressing')], max_length=1, null=True),
        ),
    ]
