# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 04:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0007_auto_20160202_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[(b'IP', b'In Progress'), (b'C', b'Complete'), (b'IR', b'In Review')], max_length=1, null=True)),
                ('priority', models.CharField(choices=[(b'L', b'Low'), (b'M', b'Med'), (b'H', b'High')], max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='todos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='digiapi.Todo'),
            preserve_default=False,
        ),
    ]
