# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0008_auto_20160202_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[(b'P', b'In Progress'), (b'C', b'Complete'), (b'R', b'In Review')], max_length=1, null=True),
        ),
    ]
