# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0009_auto_20160202_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'/Users/adaro/AWS/aws-django/eb_django_app/static/img')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='photos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='digiapi.Photo'),
            preserve_default=False,
        ),
    ]
