# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0010_auto_20160203_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='digiapi.Photo'),
        ),
    ]
