# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0012_auto_20160203_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='related_project_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
