# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0013_photo_related_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='todos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digiapi.Todo'),
        ),
    ]
