# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0014_auto_20160203_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to=b'/Users/adaro/AWS/aws-django/eb_django_app/static/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digiapi.Photo'),
        ),
    ]
