# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0016_auto_20160213_1828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together=set([('detail', 'status', 'priority')]),
        ),
    ]
