# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0017_auto_20160213_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='todos',
        ),
        migrations.AddField(
            model_name='project',
            name='todos',
            field=models.ManyToManyField(blank=True, null=True, to='digiapi.Todo'),
        ),
    ]
