# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0019_auto_20160213_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='related_project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='photos',
        ),
        migrations.AddField(
            model_name='project',
            name='photos',
            field=models.ManyToManyField(blank=True, to='digiapi.Photo'),
        ),
    ]
