# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0020_auto_20160213_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='/Users/adaro/PycharmProjects/DIGIBOARD/static/img/digiboard'),
        ),
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(null=True, upload_to='/Users/adaro/PycharmProjects/DIGIBOARDeb_django_app/static/img/photos/'),
        ),
    ]
