# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0022_auto_20160724_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(null=True, upload_to='/Users/adaro/PycharmProjects/DIGIBOARD/eb_django_app/static/img/'),
        ),
    ]
