# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0023_auto_20160724_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, storage='FS', upload_to='/Users/adaro/PycharmProjects/DIGIBOARD/static/img/digiboard'),
        ),
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(blank=True, null=True, storage='FS', upload_to='/Users/adaro/PycharmProjects/DIGIBOARD/eb_django_app/static/img/'),
        ),
    ]
