# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0024_auto_20160724_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/Users/adaro/PycharmProjects/DIGIBOARD/static/img/digiboard'),
        ),
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
