# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapi', '0025_auto_20160725_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
